context.modules = [
  { name = libpipewire-module-rt
    args = {
      nice.level     = -11
      rt.prio        = 88
      rt.time.soft   = 200000
      rt.time.hard   = 200000
      rlimits.enabled = true
      rtportal.enabled = true
      rtkit.enabled    = true
    }
    flags = [ ifexists nofail ]
  }
]
